#====单节点====
server:
  port: 8761
# 服务注册相关配置
eureka:
  # 服务实例主机名
  instance:
    hostname: discovery1
  # 服务提供者配置
  client:
    # 不进行注册,本身是注册中心
    registerWithEureka: false
    # 不获取注册信息
    fetchRegistry: false
    # 服务注册中心地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #设为false，关闭自我保护
    enable-self-preservation: false
    #检测间隔（单位毫秒，默认是1分钟）
#    evictionIntervalTimerInMs: 4000 #设置4秒

#springboo admin监控平台
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
#引入自定义属性
student:
  name: 张三
  age: 22
  score:
    shuxue: 89
    yingyu: 67
    yuwen: 83