server:
  port: 9001
spring:
  application:
    name: dynamiczuul   #最后读的是github上的  dynamiczuul-dev.yml  只有路由放在git上动态路由
  #处理中文乱码
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  boot:
    admin:
      client:
        url: http://localhost:8769
#服务的注册与发现
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
webconfig:
  nname: 配置中心有这个不管用