#前缀
server:
  port: 9000
zuul:
  #  ignored-services: '*'   # 使用'*'可忽略所有微服务
  prefix: /v1
  strip-prefix: true #是否移除前缀，这样实际请求过滤后就不带前缀了
  routes:
    xxx:
      path: /forward-mycontroller/**
      url: forward:/myContorller
    consumer-service:
      path: /xiaofei/**
      service-id: consumer-service
  sensitive-headers:     #后面配置上token打开，header的key为token的就不能往后面服务传递了

spring:
  application:
    name: zuul9000
  #处理中文乱码
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  boot:
    admin:
      client:
        url: http://localhost:8769
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  #    hostname: localhost
  #    instance-id: online-taxi-zuul-9000
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://discovery1:8761}/eureka/
#springboot-admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#logging:
#  level:
#    root: debug
